Aug05
OlgaPa95/js-wdio-2022 pull request #1
Opened 2022-08-16 03:06 UTC by OlgaPa95

2022-08-16 22:24 UTC, ahsansiddiki requested changes
Hi Olga, pls exclude node_modules folder from PR. You can add the folder into .gitignore

2022-08-17 00:44 UTC, OlgaPa95 commented
Thank you for your feedback, Ahsan. I noticed that after the push and was
wondering what is right to do in that case. I will redo that and make a
pull request after .

On Tue, Aug 16, 2022 at 17:25 Ahsan Siddiki ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Olga, pls exclude node_modules folder from PR. You can add the folder
> into .gitignore
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OlgaPa95/js-wdio-2022/pull/1#pullrequestreview-1074840865>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZZFAOP7LSUOCJ6UKKNQFE3VZQIMNANCNFSM56UFLKAA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-17 16:54 UTC, OlgaPa95 commented
Hey Ahsan, I was trying to figure out how I can exclude the node_modules
folder from PR and I'm a little confused. Could you help me with that? Can
I do that in gitHub or should I exclude that from IDE, and then commit
again?

вт, 16 авг. 2022 г. в 19:44, Olga Paraschiv ***@***.***>:

> Thank you for your feedback, Ahsan. I noticed that after the push and was
> wondering what is right to do in that case. I will redo that and make a
> pull request after .
>
> On Tue, Aug 16, 2022 at 17:25 Ahsan Siddiki ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi Olga, pls exclude node_modules folder from PR. You can add the folder
>> into .gitignore
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/OlgaPa95/js-wdio-2022/pull/1#pullrequestreview-1074840865>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZZFAOP7LSUOCJ6UKKNQFE3VZQIMNANCNFSM56UFLKAA>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-08-17 21:19 UTC, ahsansiddiki commented on test/specs/Class3/Homework.js
> +            const errorMsg = await $('._9ay7').getText();
This class value looks like random, try to use a more reliable one.

2022-08-17 21:19 UTC, ahsansiddiki commented on test/specs/Class3/Homework.js
> +        expect(pageTitle, ' Wrong location displayed').to.equal(expectedPageTitle);
For this test it doesn't make sense to me to verify pageTitle. I would request to validate whether temp displayed or not?

2022-08-17 21:20 UTC, ahsansiddiki approved these changes

2022-08-17 21:20 UTC, merged